### PR TITLE
Add MLP-based rainfall detection with scikit-learn backend

### PR DESCRIPTION
**Pull request by eoydvin**
Changes the backend of the MLP-based rainfall detection method from tensorflow to sklearn and adds two online rainfall detection methods to the MLP module. Also removes tensorflow from requirements.txt as suggested in #152.

### CODE REVIEW

**Comment by cchwala** [comment]
Thanks for this large update!

Quick comment. This text in the notebook should be updated to state that your method is now also there

> Update: As tensorflow was removed, so were the methods using neural networks. Hence only one method (the rolling standard deviation method) is shown here.

**Comment by cchwala** [comment]
By the way, it is not a problem that the docs do not build here. I fixed that in #154 and things will run fine when merged. Our docs are not really nice here anyway...

**Comment by eoydvin** [comment]
I added an rolling median baseline estimation example to the notebook. It is not really tested, but looks nicer in the plots when the wet periods are determined using the MLPs

**Comment by cchwala** [comment]
The updated explanation text in the notebook looks good now!

But I am not sure if the rolling median baseline is such a good choice. Strange things can happen, as your second example shows:

Bildschirmfoto 2024-10-10 um 23 03 30

The baseline drops below the TL of the last dry period immediately at the start of the event. Or it suddenly drops during an event. 

All baseline estimations are wrong, but the assumption that the baseline starts at the TL of the last dry data point (or an average of e.g. 5 of these) is a pretty solid one.

But I am open to discuss different options of baseline estimation. Ideally we could have a separate notebook on that. We can discuss that first on another channel and then proceed here.

**Comment by cchwala** [comment]
Thanks for the update.

Just one note regarding my last comment

> All baseline estimations are wrong, but the assumption that the baseline starts at the TL of the last dry data point (or an average of e.g. 5 of these) is a pretty solid one.

One problem with setting the baseline to the last dry TL data is that the baseline is set too high when there is a fairly short (5 minutes or maybe even more) dry data period in between two rain events. There, WAA is most likely still affecting the baseline. As a result, when the new event starts and the baseline is set again, with our current approaches, WAA is added on top of this new baseline (which was already affected by WAA). This happens especially for wet-dry classification methods which are good in detecting the intermittency of rain events, like your MLP method, or also a radar-based wet-dry classification. The smoother estimations from rolling std-dev or the CNN method do not reset the baseline that often.

As a conclusion: With improved wet-dry classification, regarding more accurate detection of start and end of events and short dry intermittent periods, we have to combine baseline estimation and WAA estimation to account for prevailing WAA during dry periods. Alternatively, we could smooth out wet-dry classification to not reset baseline for dry periods up to a certain lenght, e.g. 5 minutes.

**Comment by cchwala** [comment]
Thanks @eoydvin! Merging now 🎉

**Pull request merged**
