### PR TITLE
[WIP] overhaul of the old sphinx documentation

### PR DESCRIPTION
**Pull request by jpolz**
To be done:

- [x]  setup sphinx

- [x]  add docs_requirements.txt

- [x] create a locally working docs page

- [x] render README.md in the rst environment

- [x] find a method to add all submodules/functions automatically

- [x] find a suitable host for the docs and add config files if necessary

### CODE REVIEW

**Comment by jpolz** [comment]
just added a .readthedocs.yaml and the readthedocs theme (sphinx_rtd_theme). The toctree needs debugging to find all the modules in /source. No idea why they are not detected

**Comment by jpolz** [comment]
the tensorflow-estimator issue should not occur with tensorflow 1.14.

**Comment by jpolz** [comment]
unresolved warnings:
```
/home/polz-j/code/pycomlink/pycomlink/processing/k_R_relation.py:docstring of pycomlink.processing.k_R_relation.calc_R_from_A_min_max:3: WARNING: Unexpected indentation.
/home/polz-j/code/pycomlink/pycomlink/processing/wet_antenna.py:docstring of pycomlink.processing.wet_antenna.waa_leijnse_2008_from_A_obs:3: WARNING: Unknown target name: "1".
/home/polz-j/code/pycomlink/pycomlink/processing/wet_antenna.py:docstring of pycomlink.processing.wet_antenna.waa_leijnse_2008_from_A_obs:7: WARNING: Unknown target name: "1".
/home/polz-j/code/pycomlink/pycomlink/processing/wet_antenna.py:docstring of pycomlink.processing.wet_antenna.waa_schleiss_2013:13: WARNING: Unknown target name: "1".
/home/polz-j/code/pycomlink/pycomlink/spatial/idw.py:docstring of pycomlink.spatial.idw.Invdisttree:11: WARNING: Unexpected indentation.
/home/polz-j/code/pycomlink/pycomlink/spatial/idw.py:docstring of pycomlink.spatial.idw.Invdisttree:15: WARNING: Unexpected indentation.
/home/polz-j/code/pycomlink/pycomlink/spatial/idw.py:docstring of pycomlink.spatial.idw.Invdisttree:28: WARNING: Unexpected indentation.
/home/polz-j/code/pycomlink/pycomlink/spatial/idw.py:docstring of pycomlink.spatial.idw.Invdisttree:35: WARNING: Unexpected indentation.
/home/polz-j/code/pycomlink/pycomlink/spatial/idw.py:docstring of pycomlink.spatial.idw.Invdisttree:38: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/polz-j/code/pycomlink/pycomlink/spatial/idw.py:docstring of pycomlink.spatial.idw.Invdisttree:49: WARNING: Unexpected indentation.
/home/polz-j/code/pycomlink/pycomlink/spatial/idw.py:docstring of pycomlink.spatial.idw.Invdisttree:51: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/polz-j/code/pycomlink/pycomlink/spatial/idw.py:docstring of pycomlink.spatial.idw.Invdisttree:28: WARNING: Undefined substitution referenced: "interpol 6 - interpol 8".
/home/polz-j/code/pycomlink/pycomlink/spatial/idw.py:docstring of pycomlink.spatial.idw.Invdisttree:28: WARNING: Undefined substitution referenced: "f - interpol*".
/home/polz-j/code/pycomlink/pycomlink/util/maintenance.py:docstring of pycomlink.util.maintenance.deprecated:3: WARNING: Unexpected indentation.
/home/polz-j/code/pycomlink/pycomlink/validation/stats.py:docstring of pycomlink.validation.stats.RainError:40: WARNING: Footnote [1] is not referenced.
```

**Comment by cchwala** [comment]
Thanks @jpolz 

That is a very good start. We will have to improve the docs further in another PR.

**Pull request merged**
