### PR TITLE
Add badges to readme and move CI to github actions

### PR DESCRIPTION
**Pull request by maxmargraf**
The goal of this PR is to
* update readme for readthedocs and zenodo doi badges 
* integrate github actions for pytest and codecov

### CODE REVIEW

**Comment by cchwala** [comment]
TravisCI is still triggered. You will have to remove its yaml file

**Comment by maxmargraf** [comment]
> TravisCI is still triggered. You will have to remove its yaml file

Yup, I want to make sure everything is working before I remove TravisCI. Also I want to try to migrate codecov to github actions.

**Comment by maxmargraf** [comment]
So far this PR
* updated the readme file which now includes badges for the build status of readthedocs and a a zenodo doi badge
* integrates github actions for pytest and codecov
* therefore TravisCI was removed

**Comment by cchwala** [comment]
Would it be possible to do the test for python 3.7, 3.8 and 3.9 as it was done in the latest setup for TravisCI? This not crucial, but who knows what breaks with different conda package versions in different python versions...

**Comment by maxmargraf** [comment]
Yes, the tests are now performed for the three python versions.

**Comment by cchwala** [comment]
Thanks @maxmargraf 👍

**Pull request merged**
